
START TRANSACTION;

INSERT INTO `plugin_base_multi_lang` (`id`, `foreign_id`, `model`, `locale`, `field`, `content`, `source`) VALUES
(NULL, 1, 'pjNotification', '::LOCALE::', 'subject', 'Confirmation message', 'script'),
(NULL, 1, 'pjNotification', '::LOCALE::', 'message', '<p>You''ve just made a booking.<br /><br />Personal details:<br />Title: {Title}<br />First Name: {FirstName}<br />Last Name: {LastName}<br />E-Mail: {Email}<br />Phone: {Phone}<br />Notes: {Notes}<br />Country: {Country}<br />City: {City}<br />State: {State}<br />Zip: {Zip}<br />Address: {Address}<br />Company: {Company}<br /><br />Booking details:<br />Date/Time From: {DtFrom}<br />Table: {Table}<br />People: {People}<br />Booking ID: {BookingID}<br />Unique ID: {UniqueID}<br />Total: {Total}<br /><br />If you want to cancel your booking follow next link: {CancelURL}<br /><br />Thank you, we will contact you ASAP.</p>', 'script'),
(NULL, 2, 'pjNotification', '::LOCALE::', 'subject', 'Payment message', 'script'),
(NULL, 2, 'pjNotification', '::LOCALE::', 'message', '<p>You''ve just made a booking.<br /><br />Personal details:<br />Title: {Title}<br />First Name: {FirstName}<br />Last Name: {LastName}<br />E-Mail: {Email}<br />Phone: {Phone}<br />Notes: {Notes}<br />Country: {Country}<br />City: {City}<br />State: {State}<br />Zip: {Zip}<br />Address: {Address}<br />Company: {Company}<br /><br />Booking details:<br />Date/Time From: {DtFrom}<br />Table: {Table}<br />People: {People}<br />Booking ID: {BookingID}<br />Unique ID: {UniqueID}<br />Total: {Total}<br /><br />If you want to cancel your booking follow next link: {CancelURL}<br /><br />Thank you, we will contact you ASAP.</p>', 'script'),
(NULL, 3, 'pjNotification', '::LOCALE::', 'subject', 'Enquiry message', 'script'),
(NULL, 3, 'pjNotification', '::LOCALE::', 'message', '<p>You''ve just made an enquiry.<br /><br />Personal details:<br />Title: {Title}<br />First Name: {FirstName}<br />Last Name: {LastName}<br />E-Mail: {Email}<br />Phone: {Phone}<br />Notes: {Notes}<br />Country: {Country}<br />City: {City}<br />State: {State}<br />Zip: {Zip}<br />Address: {Address}<br />Company: {Company}<br /><br />Enquiry details:<br />Date/Time From: {DtFrom}<br />People: {People}<br />Unique ID: {UniqueID}<br /><br />If you want to cancel your enquiry follow next link: {CancelURL}<br /><br />Thank you, we will contact you ASAP.</p>', 'script'),
(NULL, 4, 'pjNotification', '::LOCALE::', 'subject', 'Cancel booking message', 'script'),
(NULL, 4, 'pjNotification', '::LOCALE::', 'message', '<p>You''ve just cancel a booking.<br /><br />Personal details:<br />Title: {Title}<br />First Name: {FirstName}<br />Last Name: {LastName}<br />E-Mail: {Email}<br />Phone: {Phone}<br />Notes: {Notes}<br />Country: {Country}<br />City: {City}<br />State: {State}<br />Zip: {Zip}<br />Address: {Address}<br />Company: {Company}<br /><br />Booking details:<br />Date/Time From: {DtFrom}<br />Table: {Table}<br />People: {People}<br />Booking ID: {BookingID}<br />Unique ID: {UniqueID}<br />Total: {Total}<br /><br />Thank you!</p>', 'script'),
(NULL, 5, 'pjNotification', '::LOCALE::', 'subject', 'Confirmation message', 'script'),
(NULL, 5, 'pjNotification', '::LOCALE::', 'message', '<p>You''ve just received a booking.<br /><br />Personal details:<br />Title: {Title}<br />First Name: {FirstName}<br />Last Name: {LastName}<br />E-Mail: {Email}<br />Phone: {Phone}<br />Notes: {Notes}<br />Country: {Country}<br />City: {City}<br />State: {State}<br />Zip: {Zip}<br />Address: {Address}<br />Company: {Company}<br /><br />Booking details:<br />Date/Time From: {DtFrom}<br />Table: {Table}<br />People: {People}<br />Booking ID: {BookingID}<br />Unique ID: {UniqueID}<br />Total: {Total}<br /><br />Thank you!</p>', 'script'),
(NULL, 6, 'pjNotification', '::LOCALE::', 'subject', 'Payment message', 'script'),
(NULL, 6, 'pjNotification', '::LOCALE::', 'message', '<p>You''ve just receive the payment for the following booking.<br /><br />Personal details:<br />Title: {Title}<br />First Name: {FirstName}<br />Last Name: {LastName}<br />E-Mail: {Email}<br />Phone: {Phone}<br />Notes: {Notes}<br />Country: {Country}<br />City: {City}<br />State: {State}<br />Zip: {Zip}<br />Address: {Address}<br />Company: {Company}<br /><br />Booking details:<br />Date/Time From: {DtFrom}<br />Table: {Table}<br />People: {People}<br />Booking ID: {BookingID}<br />Unique ID: {UniqueID}<br />Total: {Total}<br /><br /><br />Thank you!</p>', 'script'),
(NULL, 7, 'pjNotification', '::LOCALE::', 'subject', 'Enquiry message', 'script'),
(NULL, 7, 'pjNotification', '::LOCALE::', 'message', '<p>You''ve just received an enquiry.<br /><br />Personal details:<br />Title: {Title}<br />First Name: {FirstName}<br />Last Name: {LastName}<br />E-Mail: {Email}<br />Phone: {Phone}<br />Notes: {Notes}<br />Country: {Country}<br />City: {City}<br />State: {State}<br />Zip: {Zip}<br />Address: {Address}<br />Company: {Company}<br /><br />Enquiry details:<br />Date/Time From: {DtFrom}<br />People: {People}<br />Unique ID: {UniqueID}<br /><br /><br />Thank you!</p>', 'script'),
(NULL, 8, 'pjNotification', '::LOCALE::', 'subject', 'Cancel booking message', 'script'),
(NULL, 8, 'pjNotification', '::LOCALE::', 'message', '<p>A booking has been cancelled.<br /><br />Personal details:<br />Title: {Title}<br />First Name: {FirstName}<br />Last Name: {LastName}<br />E-Mail: {Email}<br />Phone: {Phone}<br />Notes: {Notes}<br />Country: {Country}<br />City: {City}<br />State: {State}<br />Zip: {Zip}<br />Address: {Address}<br />Company: {Company}<br /><br />Booking details:<br />Date/Time From: {DtFrom}<br />Table: {Table}<br />People: {People}<br />Booking ID: {BookingID}<br />Unique ID: {UniqueID}<br />Total: {Total}<br /><br />Thank you!</p>', 'script');

COMMIT;